" Starting from Scratch Vimrc 2020-04-02
" vim:foldmethod=marker

let mapleader="\<Space>"

if ! filereadable(expand('~/.vim/autoload/plug.vim'))
	echo "Downloading junegunn/vim-plug to manage plugins..."
	silent !mkdir -p ~/.vim/autoload
	silent !curl https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim > ~/.vim/autoload/plug.vim
endif

call plug#begin('~/.vim/plugged')
    Plug 'reedes/vim-pencil'
    Plug 'aarleks/zettel.vim'
    Plug 'junegunn/fzf.vim'
    Plug 'junegunn/goyo.vim'
    " COLOURS--------------------
    Plug 'logico/typewriter-vim'
    Plug 'swalladge/paper.vim'
    Plug 'romainl/Apprentice'
    Plug 'reedes/vim-colors-pencil'
    Plug 'otherjoel/vim-pollen'
    Plug 'wlangstroth/vim-racket'
call plug#end()

source $VIMRUNTIME/defaults.vim

autocmd BufWritePost ~/.vim/vimrc source $MYVIMRC

set ignorecase
set smartcase
set laststatus=2
set path+=**
set splitbelow splitright
set scrolloff=5
set wildmode=longest,list,full

augroup search
	autocmd!
	autocmd CmdlineEnter /,\? :set hlsearch
	autocmd CmdlineLeave /,\? :set nohlsearch
augroup END

runtime macros/matchit.vim

"colorscheme pencil
colorscheme apprentice

highlight Comment cterm=italic

let g:zettelkasten = '$HOME/Dropbox/Zettelkasten/'

augroup pencil
	autocmd!
	autocmd FileType markdown call pencil#init({'wrap': 'soft'})
augroup END
