#!/bin/sh

function ahead_behind {
	local count='';
	curr_branch=$(git rev-parse --abbrev-ref HEAD);
	curr_remote=$(git config branch.$curr_branch.remote);
	curr_merge_branch=$(git config branch.$curr_branch.merge | cut -d / -f 3);
	master_branch=$(git rev-list --left-right --count $curr_branch...$curr_remote/$curr_merge_branch | tr -s '\t' '|');
	if $(git rev-list upstream/master &>/dev/null); then
		count+="$(git rev-list --left-right --count master...upstream/master | awk '{print $2}')|";
	fi;
	count+=$master_branch

#if [ $(git branch -a | grep upstream | wc -l) > 0 ]; then
#	upstream_master=$(git rev-list --count master...upstream/master &>/dev/null);
#fi;

        echo $count
}

echo $(ahead_behind)
