#!/bin/bash

# This script is called by i3 on startup.

# Map the caps lock key to super
setxkbmap -layout us -option caps:super
xcape -e 'Super_L=Escape'

# Map the menu button to right super as well.
xmodmap -e 'keycode 135 = Super_R'
#keycode 135 = Super_R NoSymbol Super_R
