#!/usr/bin/env bash

# Moves the branch to master and pulls the latest repo and rebases the branches.
# This script copied directly from https://gitlab.com/uoou/dotfiles/blob/master/bin/suckrebase

git checkout master &&

make clean && rm -f config.h && git reset --hard origin/master && git pull &&

for branch in $(git for-each-ref --format='%(refname)' refs/heads/ | cut -d'/' -f3); do
    if [ "$branch" != "master" ];then
	git checkout $branch && git rebase --preserve-merges master
    fi
done


