#!/usr/bin/env bash

# Makes clean and resets the master branch, and then produces a diff file for
# each branch in a suckless project folder.
# This script copied directly from https://gitlab.com/uoou/dotfiles/tree/master/bin

# Must be in the project directory to run; i.e. in  /suckless/st/

git checkout master &&
dotfiles="$HOME/.config/suckless"
project=$(basename $(pwd))
diffdir="${dotfiles}/${project}_diffs/"
olddiffdir="${dotfiles}/${project}_diffs/old/"

rm -rf "$olddiffdir" &&
mkdir -p "$olddiffdir" &&
mkdir -p "$diffdir" &&
mv "$diffdir"*.diff "$olddiffdir" || true &&

make clean && rm -f config.h && git reset --hard origin/master &&

for branch in $(git for-each-ref --format='%(refname)' refs/heads/ | cut -d'/' -f3); do
    if [ "$branch" != "master" ]; then
	git diff master..$branch > "${diffdir}${project}_${branch}.diff"
    fi
done


